function abbreviations --on-event fish_prompt
    # ----- git aliases -----
    abbr --add s "git status"
    abbr --add c "git commit"
    abbr --add commit "git commit"
    abbr --add changes "git diff"
    abbr --add b "git branch"
    abbr --add branch "git branch"
    abbr --add add "git add"
    abbr --add co "git checkout"
    abbr --add checkout "git checkout"
    abbr --add log "git log"
    abbr --add lg "git lg"
    abbr --add lgm "git lgmerge"
    abbr --add lgmerge "git lgmerge"
    abbr --add lgmine "git lgmine"
    abbr --add merge "git merge"
    abbr --add pull "git pull"
    abbr --add push "git push"
    abbr --add force "git push --force-with-lease"
    abbr --add rebase "git rebase"
    abbr --add reset "git reset"
    abbr --add hard "git reset --hard"
    abbr --add soft "git reset --soft"
    abbr --add clean "git clean -dff"
    abbr --add show "git show"
    abbr --add tag "git tag"
    abbr --add remove "git rm"
    abbr --add move "git mv"
    abbr --add stash "git stash"
    abbr --add pop "git stash pop"
    abbr --add clone "git clone"
    abbr --add remote "git remote"
    abbr --add revert "git revert"
    abbr --add fetch "git fetch"
    abbr --add amend "git commit --amend"
    abbr --add pick "git cherry-pick"
    abbr --add cherry "git cherry-pick"
    abbr --add ci "git ci"
    abbr --add di "git di"

    abbr --add ll "ls -Alrth"
    abbr --add mkdirs "mkdir -p" # make intermediary directories
    abbr --add k kubectl
    abbr --add pubkey "cat ~/.ssh/id_rsa.pub | pbcopy"
    abbr --add ports "lsof -PiTCP -sTCP:LISTEN"
    abbr --add !! "gh copilot suggest"

    # delete itself so it is only executed once per session
    functions --erase abbreviations
end
